# Generated by Django 4.1.1 on 2022-09-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_THE_PROCESS', 'В процессе'), ('MADE', 'Сделано')], default='NEW', max_length=50, verbose_name='Статус')),
                ('execute_at', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
