# Generated by Django 4.1.1 on 2022-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Детальное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('in_the_process', 'В процессе'), ('made', 'Сделано')], default='Новая', max_length=50, verbose_name='Статус'),
        ),
    ]
